import { Finger, Hand, KeyObj } from '../types';

export const DVORAK_LAYOUT: KeyObj[][] = [
    [
        { label: 'Esc', size: 'w-1/12', key: 'Esc' },
        { label: 'F2', size: 'w-1/12', key: 'F2' },
        { label: 'F3', size: 'w-1/12', key: 'F3' },
        { label: 'F4', size: 'w-1/12', key: 'F4' },
        { label: 'F5', size: 'w-1/12', key: 'F5' },
        { label: 'F6', size: 'w-1/12', key: 'F6' },
        { label: 'F7', size: 'w-1/12', key: 'F7' },
        { label: 'F8', size: 'w-1/12', key: 'F8' },
        { label: 'F9', size: 'w-1/12', key: 'F9' },
        { label: 'F10', size: 'w-1/12', key: 'F10' },
        { label: 'F11', size: 'w-1/12', key: 'F11' },
        { label: 'F12', size: 'w-1/12', key: 'F12' },
    ],
    [
        { label: '`', size: 'w-1/12', key: '`', altLabel: '~' },
        {
            label: '1',
            size: 'w-1/12',
            key: '1',
            altLabel: '!',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: '2',
            size: 'w-1/12',
            key: '2',
            altLabel: '@',
            hand: Hand.Left,
            finger: Finger.Ring,
        },
        {
            label: '3',
            size: 'w-1/12',
            key: '3',
            altLabel: '#',
            hand: Hand.Left,
            finger: Finger.Middle,
        },
        {
            label: '4',
            size: 'w-1/12',
            key: '4',
            altLabel: '$',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: '5',
            size: 'w-1/12',
            key: '5',
            altLabel: '%',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: '6',
            size: 'w-1/12',
            key: '6',
            altLabel: '^',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: '7',
            size: 'w-1/12',
            key: '7',
            altLabel: '&',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: '8',
            size: 'w-1/12',
            key: '8',
            altLabel: '*',
            hand: Hand.Right,
            finger: Finger.Middle,
        },
        {
            label: '9',
            size: 'w-1/12',
            key: '9',
            altLabel: '(',
            hand: Hand.Right,
            finger: Finger.Ring,
        },
        {
            label: '0',
            size: 'w-1/12',
            key: '0',
            altLabel: ')',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '[',
            size: 'w-1/12',
            key: '[',
            altLabel: '{',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: ']',
            size: 'w-1/12',
            key: ']',
            altLabel: '}',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Backspace',
            size: 'w-2/12',
            key: 'Backspace',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
    [
        {
            label: 'Tab',
            size: 'w-2/12',
            key: 'Tab',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: "'",
            size: 'w-1/12',
            key: "'",
            altLabel: '"',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: ',',
            size: 'w-1/12',
            key: ',',
            altLabel: '<',
            hand: Hand.Left,
            finger: Finger.Ring,
        },
        {
            label: '.',
            size: 'w-1/12',
            key: '.',
            altLabel: '>',
            hand: Hand.Left,
            finger: Finger.Middle,
        },
        {
            label: 'P',
            size: 'w-1/12',
            key: 'P',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'Y',
            size: 'w-1/12',
            key: 'Y',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'F',
            size: 'w-1/12',
            key: 'F',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'G',
            size: 'w-1/12',
            key: 'G',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'C',
            size: 'w-1/12',
            key: 'C',
            hand: Hand.Right,
            finger: Finger.Middle,
        },
        {
            label: 'R',
            size: 'w-1/12',
            key: 'R',
            hand: Hand.Right,
            finger: Finger.Ring,
        },
        {
            label: 'L',
            size: 'w-1/12',
            key: 'L',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '/',
            size: 'w-1/12',
            key: '/',
            altLabel: '?',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '=',
            size: 'w-1/12',
            key: '=',
            altLabel: '+',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '\\',
            size: 'w-1/12',
            key: '\\',
            altLabel: '|',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
    [
        {
            label: 'Caps',
            size: 'w-2/12',
            key: 'Caps',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'A',
            size: 'w-1/12',
            key: 'A',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'O',
            size: 'w-1/12',
            key: 'O',
            hand: Hand.Left,
            finger: Finger.Ring,
        },
        {
            label: 'E',
            size: 'w-1/12',
            key: 'E',
            hand: Hand.Left,
            finger: Finger.Middle,
        },
        {
            label: 'U',
            size: 'w-1/12',
            key: 'U',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'I',
            size: 'w-1/12',
            key: 'I',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'D',
            size: 'w-1/12',
            key: 'D',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'H',
            size: 'w-1/12',
            key: 'H',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'T',
            size: 'w-1/12',
            key: 'T',
            hand: Hand.Right,
            finger: Finger.Middle,
        },
        {
            label: 'N',
            size: 'w-1/12',
            key: 'N',
            hand: Hand.Right,
            finger: Finger.Ring,
        },
        {
            label: 'S',
            size: 'w-1/12',
            key: 'S',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '-',
            size: 'w-1/12',
            key: '-',
            altLabel: '_',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Enter',
            size: 'w-2/12',
            key: 'Enter',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
    [
        {
            label: 'Shift',
            size: 'w-2/12',
            key: 'Shift',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: ';',
            size: 'w-1/12',
            key: ';',
            altLabel: ':',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'Q',
            size: 'w-1/12',
            key: 'Q',
            hand: Hand.Left,
            finger: Finger.Ring,
        },
        {
            label: 'J',
            size: 'w-1/12',
            key: 'J',
            hand: Hand.Left,
            finger: Finger.Middle,
        },
        {
            label: 'K',
            size: 'w-1/12',
            key: 'K',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'X',
            size: 'w-1/12',
            key: 'X',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'B',
            size: 'w-1/12',
            key: 'B',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'M',
            size: 'w-1/12',
            key: 'M',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'W',
            size: 'w-1/12',
            key: 'W',
            hand: Hand.Right,
            finger: Finger.Middle,
        },
        {
            label: 'V',
            size: 'w-1/12',
            key: 'V',
            hand: Hand.Right,
            finger: Finger.Ring,
        },
        {
            label: 'Z',
            size: 'w-1/12',
            key: 'Z',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Shift',
            size: 'w-2/12',
            key: 'Shift',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
    [
        {
            label: 'Ctrl',
            size: 'w-2/12',
            key: 'Ctrl',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'Win',
            size: 'w-1/12',
            key: 'Win',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'Alt',
            size: 'w-2/12',
            key: 'Alt',
            hand: Hand.Left,
            finger: Finger.Thumb,
        },
        {
            label: 'Space',
            size: 'w-6/12',
            key: ' ',
            hand: Hand.Left && Hand.Right,
            finger: Finger.Thumb,
        },
        {
            label: 'Alt',
            size: 'w-2/12',
            key: 'Alt',
            hand: Hand.Right,
            finger: Finger.Thumb,
        },
        {
            label: 'Win',
            size: 'w-1/12',
            key: 'Win',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Fn',
            size: 'w-1/12',
            key: 'Fn',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Ctrl',
            size: 'w-2/12',
            key: 'Ctrl',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
];
export const QWERTY_LAYOUT: KeyObj[][] = [
    [
        { label: 'Esc', size: 'w-1/12', key: 'Esc' },
        { label: 'F2', size: 'w-1/12', key: 'F2' },
        { label: 'F3', size: 'w-1/12', key: 'F3' },
        { label: 'F4', size: 'w-1/12', key: 'F4' },
        { label: 'F5', size: 'w-1/12', key: 'F5' },
        { label: 'F6', size: 'w-1/12', key: 'F6' },
        { label: 'F7', size: 'w-1/12', key: 'F7' },
        { label: 'F8', size: 'w-1/12', key: 'F8' },
        { label: 'F9', size: 'w-1/12', key: 'F9' },
        { label: 'F10', size: 'w-1/12', key: 'F10' },
        { label: 'F11', size: 'w-1/12', key: 'F11' },
        { label: 'F12', size: 'w-1/12', key: 'F12' },
    ],
    [
        { label: '`', size: 'w-1/12', key: '`', altLabel: '~' },
        {
            label: '1',
            size: 'w-1/12',
            key: '1',
            altLabel: '!',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: '2',
            size: 'w-1/12',
            key: '2',
            altLabel: '@',
            hand: Hand.Left,
            finger: Finger.Ring,
        },
        {
            label: '3',
            size: 'w-1/12',
            key: '3',
            altLabel: '#',
            hand: Hand.Left,
            finger: Finger.Middle,
        },
        {
            label: '4',
            size: 'w-1/12',
            key: '4',
            altLabel: '$',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: '5',
            size: 'w-1/12',
            key: '5',
            altLabel: '%',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: '6',
            size: 'w-1/12',
            key: '6',
            altLabel: '^',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: '7',
            size: 'w-1/12',
            key: '7',
            altLabel: '&',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: '8',
            size: 'w-1/12',
            key: '8',
            altLabel: '*',
            hand: Hand.Right,
            finger: Finger.Middle,
        },
        {
            label: '9',
            size: 'w-1/12',
            key: '9',
            altLabel: '(',
            hand: Hand.Right,
            finger: Finger.Ring,
        },
        {
            label: '0',
            size: 'w-1/12',
            key: '0',
            altLabel: ')',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '-',
            size: 'w-1/12',
            key: '-',
            altLabel: '_',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '=',
            size: 'w-1/12',
            key: '=',
            altLabel: '+',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Backspace',
            size: 'w-2/12',
            key: 'Backspace',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
    [
        {
            label: 'Tab',
            size: 'w-2/12',
            key: 'Tab',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'Q',
            size: 'w-1/12',
            key: 'Q',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'W',
            size: 'w-1/12',
            key: 'W',
            hand: Hand.Left,
            finger: Finger.Ring,
        },
        {
            label: 'E',
            size: 'w-1/12',
            key: 'E',
            altKey: 'Ē',
            hand: Hand.Left,
            finger: Finger.Middle,
        },
        {
            label: 'R',
            size: 'w-1/12',
            key: 'R',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'T',
            size: 'w-1/12',
            key: 'T',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'Y',
            size: 'w-1/12',
            key: 'Y',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'U',
            size: 'w-1/12',
            key: 'U',
            altKey: 'Ū',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'I',
            size: 'w-1/12',
            key: 'I',
            altKey: 'Ī',
            hand: Hand.Right,
            finger: Finger.Middle,
        },
        {
            label: 'O',
            size: 'w-1/12',
            key: 'O',
            hand: Hand.Right,
            finger: Finger.Ring,
        },
        {
            label: 'P',
            size: 'w-1/12',
            key: 'P',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '[',
            size: 'w-1/12',
            key: '[',
            altLabel: '{',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: ']',
            size: 'w-1/12',
            key: ']',
            altLabel: '}',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: '\\',
            size: 'w-1/12',
            key: '\\',
            altLabel: '|',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
    [
        {
            label: 'Caps',
            size: 'w-2/12',
            key: 'Caps',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'A',
            size: 'w-1/12',
            key: 'A',
            altKey: 'Ā',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'S',
            size: 'w-1/12',
            key: 'S',
            altKey: 'Š',
            hand: Hand.Left,
            finger: Finger.Ring,
        },
        {
            label: 'D',
            size: 'w-1/12',
            key: 'D',
            hand: Hand.Left,
            finger: Finger.Middle,
        },
        {
            label: 'F',
            size: 'w-1/12',
            key: 'F',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'G',
            size: 'w-1/12',
            key: 'G',
            altKey: 'Ģ',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'H',
            size: 'w-1/12',
            key: 'H',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'J',
            size: 'w-1/12',
            key: 'J',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'K',
            size: 'w-1/12',
            key: 'K',
            altKey: 'Ķ',
            hand: Hand.Right,
            finger: Finger.Middle,
        },
        {
            label: 'L',
            size: 'w-1/12',
            key: 'L',
            altKey: 'Ļ',
            hand: Hand.Right,
            finger: Finger.Ring,
        },
        {
            label: ';',
            size: 'w-1/12',
            key: ';',
            altLabel: ':',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: "'",
            size: 'w-1/12',
            key: "'",
            altLabel: '"',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Enter',
            size: 'w-2/12',
            key: 'Enter',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
    [
        {
            label: 'Shift',
            size: 'w-2/12',
            key: 'Shift',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'Z',
            size: 'w-1/12',
            key: 'Z',
            altKey: 'Ž',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'X',
            size: 'w-1/12',
            key: 'X',
            hand: Hand.Left,
            finger: Finger.Ring,
        },
        {
            label: 'C',
            size: 'w-1/12',
            key: 'C',
            altKey: 'Č',
            hand: Hand.Left,
            finger: Finger.Middle,
        },
        {
            label: 'V',
            size: 'w-1/12',
            key: 'V',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'B',
            size: 'w-1/12',
            key: 'B',
            hand: Hand.Left,
            finger: Finger.Index,
        },
        {
            label: 'N',
            size: 'w-1/12',
            key: 'N',
            altKey: 'Ņ',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: 'M',
            size: 'w-1/12',
            key: 'M',
            hand: Hand.Right,
            finger: Finger.Index,
        },
        {
            label: ',',
            size: 'w-1/12',
            key: ',',
            altLabel: '<',
            hand: Hand.Right,
            finger: Finger.Middle,
        },
        {
            label: '.',
            size: 'w-1/12',
            key: '.',
            altLabel: '>',
            hand: Hand.Right,
            finger: Finger.Ring,
        },
        {
            label: '/',
            size: 'w-1/12',
            key: '/',
            altLabel: '?',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Shift',
            size: 'w-2/12',
            key: 'Shift',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
    [
        {
            label: 'Ctrl',
            size: 'w-2/12',
            key: 'Ctrl',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'Win',
            size: 'w-1/12',
            key: 'Win',
            hand: Hand.Left,
            finger: Finger.Pinky,
        },
        {
            label: 'Alt',
            size: 'w-2/12',
            key: 'Alt',
            hand: Hand.Left,
            finger: Finger.Thumb,
        },
        {
            label: 'Space',
            size: 'w-6/12',
            key: ' ',
            hand: Hand.Left && Hand.Right,
            finger: Finger.Thumb,
        },
        {
            label: 'Alt',
            size: 'w-2/12',
            key: 'Alt',
            hand: Hand.Right,
            finger: Finger.Thumb,
        },
        {
            label: 'Win',
            size: 'w-1/12',
            key: 'Win',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Fn',
            size: 'w-1/12',
            key: 'Fn',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
        {
            label: 'Ctrl',
            size: 'w-2/12',
            key: 'Ctrl',
            hand: Hand.Right,
            finger: Finger.Pinky,
        },
    ],
];
